language: scala
scala:
- 2.12.7
script:
- sbt assembly
before_deploy:
- mv target/scala-2.12/marathon-capabilities-plugin-assembly-*.jar marathon-capabilities-plugin.jar
deploy:
  provider: releases
  api_key:
    secure: yphGCxByF1aNcJygN10xiSVDXh/LH89ILCPiJz1zv/OBvGeL+S0FzCRtmybJGMKEKVdW3ecWCdFlP7+AqmQznDPu2XaiiUx0/D+Bo1jQEAdHcUOhk8VvnbPAPwFkv56tJEobcvaDADluo6W7Mtae/08c4SjtZhJelLTDZA4Z2WpSpMO4h5lar3og04yCWHcz/yvHOsiqyes2WZ10+vuOkS5djQRBlWGxOb7VTIuD362GTP2YdWfyh/j1FqILTihtbVBz54+XgDD5GxAqcNIBrNFWnGvAkDFICwcFYBef9yCjkTkp4a7Wjh6xQ4zLNyMg1x470YJzzWyrTbWqJjloZu76Fe9Lt/PUGtUQ8zp+oKCgAvHuKDIgzUcYlbrSKluDtQJnGYr2DFyn2ruB3pVYGQWex8WMwHV61gQBA7osDG8ZE5fbqV8mraitP+KfIeh++PeezvHbfJ/smvaXz3+y9h37Ik8u62jM03cHSyKCJwG24kHI/RKJTyzGMS/FiuugBA7dXK9sGcS55aLwfTuGSnedl0s86d1vO2XRrANYILLH93EtUKPc2bNCWAHPNNM5U9AkezAebMesrGvHgDMOmSf0TFSZyiLZlptGpadzMF5/tpQJkjAJlLdD8IPzVq9zcd/xAr8byb7E6RmwpkrIfFhhGtTrHtUQRLyQdcj/lCo=
  file: marathon-capabilities-plugin.jar
  skip_cleanup: true
  on:
    repo: criteo/marathon-capabilities-plugin
    tags: true
