version: "3"
services:
  zookeeper:
    image: zookeeper:3.4.11
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      app_net:
        ipv4_address: 172.16.191.2

  mesos-master:
    image: mesosphere/mesos-master:1.7.0
    privileged: true
    hostname: localhost
    ports:
      - "5050:5050"
    networks:
      app_net:
        ipv4_address: 172.16.191.3
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      MESOS_ZK: zk://zookeeper:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: docker-compose
      MESOS_HOSTNAME: localhost
      MESOS_WORK_DIR: /var/tmp/mesos
      MESOS_LOG_DIR: /var/log/mesos
      LIBPROCESS_IP: 172.16.191.3


  mesos-slave:
    image: mesosphere/mesos-slave:1.7.0
    privileged: true
    hostname: localhost
    ports:
      - "5051:5051"
    networks:
      app_net:
        ipv4_address: 172.16.191.4
    links:
      - zookeeper:zookeeper
      - mesos-master:master.mesos
    depends_on:
      - zookeeper
      - mesos-master
    environment:
      MESOS_MASTER: zk://zookeeper:2181/mesos
      MESOS_CONTAINERIZERS: mesos,docker
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_BOUNDING_CAPABILITIES: '{"capabilities":["NET_RAW"]}'
      MESOS_HOSTNAME: localhost
      MESOS_WORK_DIR: /var/tmp/mesos
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_SYSTEMD_ENABLE_SUPPORT: "false"
      MESOS_IMAGE_PROVIDERS: docker
      MESOS_ISOLATION: filesystem/linux,docker/runtime
      LIBPROCESS_IP: 172.16.191.4
    volumes:
      - ./test/wrapme.sh:/usr/bin/wrapme.sh
      - /var/run/docker.sock:/var/run/docker.sock

  marathon:
    image: mesosphere/marathon:v1.6.549
    entrypoint:
      - ./bin/start
      - --disable_ha
      - --plugin_conf
      - /marathon/plugins/conf/conf.json
      - --plugin_dir
      - /marathon/plugins/jar
    hostname: localhost
    ports:
     - "8080:8080"
    networks:
      app_net:
        ipv4_address: 172.16.191.5
    links:
      - zookeeper
      - mesos-master
    depends_on:
      - zookeeper
      - mesos-master
      - mesos-slave
    environment:
      - MARATHON_ZK=zk://zookeeper:2181/marathon
      - MARATHON_MASTER=zk://zookeeper:2181/mesos
      - LIBPROCESS_IP=172.16.191.5
    volumes:
      - "./src/main/resources/com/criteo/marathon/plugin-conf.json:/marathon/plugins/conf/conf.json"
      - "./target/scala-2.12/marathon-capabilities-plugin-assembly-1.0.jar:/marathon/plugins/jar/plugin.jar"

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.191.0/24
